### PR TITLE
fix latex in windows

### LINKED ISSUE #384: [BUG] latex: tex2svg might not be installed
**Describe the bug**

Unable to use LaTeX, because Julia can't find tex2svg when running it with "open". This is despite of the fact that I installed the required node module with 

`npm install -g mathjax-node-cli`

and ensured that the relevant location (AppData\Roaming\npm) is in PATH. tex2svg works fine from cmd and Powershell from any directory.

**To Reproduce**

1. Julia Version (i.e. output of `julia -v`): 1.6.2

2. Operating system (Mac, Linux, Windows): Windows 10

3. Javis version (i.e output of `] status Javis` in the REPL): 0.6.0

4. Minimum working code example that led to bug: v 0.6.0

**Expected Behavior and Actual Behavior**

Should render latex correctly and find the tex2svg program, as it is in PATH. Instead fails with a long stack trace.

**Stacktrace (If Applicable)**
```
`┌ Warning: Using LaTeX needs the program `tex2svg` which might not be installed
└ @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\latex.jl:151
[ Info: It can be installed using `npm install -g mathjax-node-cli`
ERROR: LoadError: IOError: could not spawn `tex2svg '\begin{equation}
\left[\begin{array}{cc}
2 & 3 \\  4 & \sqrt{5} \\
\end{array} \right]
\end{equation}'`: no such file or directory (ENOENT)
Stacktrace:
  [1] get_latex_svg(text::LaTeXString)
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\latex.jl:153
  [2] animate_latex(text::LaTeXString, pos::Point, t::Float64, valign::Symbol, halign::Symbol, object::Symbol)
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\latex.jl:85
  [3] latex(text::LaTeXString, pos::Point, draw_object::Symbol; valign::Symbol, halign::Symbol)
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\latex.jl:81
  [4] latex
    @ C:\Users\USER\.julia\packages\Javis\FLdWO\src\latex.jl:6 [inlined]
  [5] draw_latex(video::Video, action::Object, frame::Int64)
    @ Main C:\Users\USER\Documents\Fysiikka\latex.jl:13
  [6] draw_object(object::Object, video::Video, frame::Int64, origin_matrix::Matrix{Float64}, layer_frames::Nothing)
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:607
  [7] macro expansion
    @ C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:363 [inlined]
  [8] macro expansion
    @ C:\Users\USER\.julia\packages\Luxor\XHa4Y\src\basics.jl:520 [inlined]
  [9] render_objects(objects::Vector{Javis.AbstractObject}, video::Video, frame::Int64; layer_frames::Nothing)
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:362
 [10] render_objects
    @ C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:335 [inlined]
 [11] get_javis_frame(video::Video, objects::Vector{Javis.AbstractObject}, frame::Int64; layers::Vector{Javis.AbstractObject})
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:550
 [12] macro expansion
    @ C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:278 [inlined]
 [13] macro expansion
    @ C:\Users\USER\.julia\packages\ProgressMeter\Vf8un\src\ProgressMeter.jl:940 [inlined]
 [14] render(video::Video; framerate::Int64, pathname::String, liveview::Bool, streamconfig::Nothing, tempdirectory::String, ffmpeg_loglevel::String)
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:277
 [15] top-level scope
    @ C:\Users\USER\Documents\Fysiikka\latex.jl:28
in expression starting at C:\Users\USER\Documents\Fysiikka\latex.jl:28
```

caused by: 
```
IOError: could not spawn `tex2svg '\begin{equation}
\left[\begin{array}{cc}
2 & 3 \\  4 & \sqrt{5} \\
\end{array} \right]
\end{equation}'`: no such file or directory (ENOENT)
Stacktrace:
  [1] _spawn_primitive(file::String, cmd::Cmd, stdio::Vector{Any})
    @ Base .\process.jl:99
  [2] #637
    @ .\process.jl:112 [inlined]
  [3] setup_stdios(f::Base.var"#637#638"{Cmd}, stdios::Vector{Any})
    @ Base .\process.jl:196
  [4] _spawn
    @ .\process.jl:111 [inlined]
  [5] open(cmds::Cmd, stdio::Base.DevNull; write::Bool, read::Bool)
    @ Base .\process.jl:370
  [6] open
    @ .\process.jl:361 [inlined]
  [7] open(cmds::Cmd, mode::String, stdio::Base.DevNull)
    @ Base .\process.jl:341
  [8] read(cmd::Cmd)
    @ Base .\process.jl:410
  [9] read(cmd::Cmd, #unused#::Type{String})
    @ Base .\process.jl:421
 [10] get_latex_svg(text::LaTeXString)
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\latex.jl:149
 [11] animate_latex(text::LaTeXString, pos::Point, t::Float64, valign::Symbol, halign::Symbol, object::Symbol)
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\latex.jl:85
 [12] latex(text::LaTeXString, pos::Point, draw_object::Symbol; valign::Symbol, halign::Symbol)
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\latex.jl:81
 [13] latex
    @ C:\Users\USER\.julia\packages\Javis\FLdWO\src\latex.jl:6 [inlined]
 [14] draw_latex(video::Video, action::Object, frame::Int64)
    @ Main C:\Users\USER\Documents\Fysiikka\latex.jl:13
 [15] draw_object(object::Object, video::Video, frame::Int64, origin_matrix::Matrix{Float64}, layer_frames::Nothing)
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:607
 [16] macro expansion
    @ C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:363 [inlined]
 [17] macro expansion
    @ C:\Users\USER\.julia\packages\Luxor\XHa4Y\src\basics.jl:520 [inlined]
 [18] render_objects(objects::Vector{Javis.AbstractObject}, video::Video, frame::Int64; layer_frames::Nothing)
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:362
 [19] render_objects
    @ C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:335 [inlined]
 [20] get_javis_frame(video::Video, objects::Vector{Javis.AbstractObject}, frame::Int64; layers::Vector{Javis.AbstractObject})
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:550
 [21] macro expansion
    @ C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:278 [inlined]
 [22] macro expansion
    @ C:\Users\USER\.julia\packages\ProgressMeter\Vf8un\src\ProgressMeter.jl:940 [inlined]
 [23] render(video::Video; framerate::Int64, pathname::String, liveview::Bool, streamconfig::Nothing, tempdirectory::String, ffmpeg_loglevel::String)
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:277
 [24] top-level scope
    @ C:\Users\USER\Documents\Fysiikka\latex.jl:28`
```

**Additional context**
I should add that the rest of Javis seems to be working fine, only the LaTeX support doesn't work. Also, this problem seems to persist when trying to use 'run' from REPL, so problem might be that my Julia install is somehow configured.

Decided to post this as an issue anyway, because Javis depends on tex2svg, and I just did a clean Julia, npm and Javis install from scratch. So doing this the obvious way didn't lead to a working Javis for me.

If anyone has any ideas, greatly appreciated :)

### PR DESCRIPTION
**Pull request by gpucce**
## PR Checklist

If you are contributing to `Javis.jl`, please make sure you are able to check off each item on this list:

- [x] Did I update `CHANGELOG.md` with whatever changes/features I added with this PR?
- [x] Did I make sure to only change the part of the file where I introduced a new change/feature?
- [ ] Did I cover all corner cases to be close to 100% test coverage (if applicable)?
- [ ] Did I properly add Javis dependencies to the `Project.toml` + set an upper bound of the dependency (if applicable)?
- [ ] Did I properly add test dependencies to the `test` directory (if applicable)?
- [x] Did I check relevant tutorials that may be affected by changes in this PR?
- [ ] Did I clearly articulate why this PR was made the way it was and how it was made?

**Link to relevant issue(s)**
Closes #384 #420 

**How did you address these issues with this PR? What methods did you use?**
Replace `tex2svg $ts` with `cmd /C tex2svg $ts` because:
"On Windows, many similar commands, such as echo and dir, are not external programs and instead are built into the shell cmd.exe itself. One option to run these commands is to invoke cmd.exe, for example cmd /C echo hello."
Quote from https://docs.julialang.org/en/v1/manual/running-external-programs/#Running-External-Programs

### CODE REVIEW

File: src/latex.jl [hunk 1]
```diff
@@ -143,8 +143,13 @@ function get_latex_svg(text::LaTeXString)
     if haskey(LaTeXSVG, text)
         svg = LaTeXSVG[text]
     else
-        ts = strip_eq(text)
-        command = `tex2svg $ts`
+        command = if Sys.iswindows()
+            ts = replace(strip_eq(text), "\n" => " ")
```
Comment (Wikunia) [inline src/latex.jl:147]: Maybe put the `strip_eq` outside the if and use `ts` in both.

File: CHANGELOG.md [hunk 2]
```diff
@@ -1,4 +1,5 @@
 # Javis.jl - Changelog
+- Added fix to latex function to make it work better on Windows.
```
Comment (Wikunia) [inline CHANGELOG.md:2]: Do you mind changing this to `latex`? (in code ticks)

**Review by Wikunia — COMMENTED** [review]
Minor things and I'll test it on linux now.

**Comment by Wikunia** [comment]
Works wonderfully for me. Thank you
