### PR TITLE
Forgot to push sethue to Animations.jl

### LINKED ISSUE #151: Scaling doesn't work with Animations.jl
Merging Animations.jl and Scaling failed a bit such that Animations.jl is not supported for scaling. It's an easy fix :)

### PR DESCRIPTION
**Pull request by Wikunia**
## PR Checklist

If you are contributing to `Javis.jl`, please make sure you are able to check off each item on this list:

- [x] Did I update `CHANGELOG.md` with whatever changes/features I added with this PR?
- [x] Did I update the `TODO.md` (if applicable)?
- [x] Did I make sure to only change the part of the file where I introduced a new change/feature?
- [ ] Did I cover all corner cases to be close to 100% test coverage (if applicable)?
- [x] Did I properly add Javis dependencies to the `Project.toml` + set an upper bound of the dependency (if applicable)?
- [x] Did I properly add test dependencies to the `test` directory (if applicable)?
- [ ] Did I check relevant tutorials that may be affected by changes in this PR?
- [x] Did I clearly articulate why this PR was made the way it was and how it was made?

**Link to relevant issue(s)**
Closes #151 

**How did you address these issues with this PR? What methods did you use?**
I forgot to push `sethue` because formatting took a while and I just forgot to push! Therefore this is in addition to #125 and it also implements #151 
Let's hope all tests pass. :wink:

### CODE REVIEW

File: src/subaction_animations.jl [hunk 1]
```diff
@@ -257,3 +257,34 @@ function _scale(video, action, subaction, rel_frame)
     p = get_interpolation(subaction, rel_frame)
     scale(p)
 end
+
+"""
+    sethue()
+
+Set the color of a function defined inside a [`SubAction`](@ref) using an Animation defined
+with Animations.jl. 
+
```
Comment (TheCedarPrince) [inline src/subaction_animations.jl:266]: Hey @Wikunia , I am really have difficulty with knowing what I need to do here. I looked at `rotate` and this docstring, but I am still unclear on how to use `sethue()`. I am not sure if it would be useful to put a larger example in the `# Example` section.

Regardless, this functionality definitely needs a tutorial. Maybe we could make tutorials on the Perlin noise and the "please wait" animation you made.

**UPDATE:** I think you forgot to update the `rotate` function based on the test you came up with as `sethue()` is not used there.

**Review by TheCedarPrince — CHANGES_REQUESTED** [review]
Almost there, I think just a few changes to the docstring and we are good!

File: src/subaction_animations.jl (hunk 1 above)
Comment (Wikunia) [reply src/subaction_animations.jl:266]: Yes this needs a tutorial. I think we should make a very short example for all of them such that they show up inside the help mode of the REPL and refer to a tutorial for a bigger picture.

Comment (Wikunia) [reply src/subaction_animations.jl:266]: I've added one extra line to hopefully make it clearer and the rest should be part of a tutorial.

Comment (TheCedarPrince) [reply src/subaction_animations.jl:266]: Sounds great, this makes sense to me.

**Review by TheCedarPrince — APPROVED** [review]
This looks good. Apologies for the delay on review!
